version: "3.9"
services:
  redis-stack:
    image: redis/redis-stack:7.2.0-v12
    container_name: kaos-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
    driver: local
